name: Compiling & Run of Project
run-name: Compiling project
on:
  push:
    branches:
      - master
jobs:
  compiling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compiling
        run: |
          ls
          cd Inginious/P0
          gcc -o project project.c -g
          ./project